### ISSUE TITLE
Basic Functionality - Drivetrain

### ISSUE THREAD

**Issue by Wildcards7506** [Wildcards-7506/FRC-2023#1]
**Commands** required for:
1. Joystick control of Mecanum Drive
2. Joystick control of Tank Drive
3. Ability to switch between the two
    3a. Drop wheels _not_ required at this time

**Comment by acdelgado1019** [comment]
Current system sets each motor independently using long, hard to read lines of code.
Need to shift to using the drive method in Drivetrain.java
Note - the drive method arguments are forward/backward, side to side, rotation, and field relative.
Field relative is true for mecanum, false for tank
