### ISSUE TITLE
Basic Functionality - Crane

### ISSUE THREAD

**Issue by Wildcards7506** [Wildcards-7506/FRC-2023#3]
Methods required for:
1. Rotate arm to set position (degrees)
2. Extend jackscrew to set position (inches)
3. open/close claw

Additional tasks:
- Determine Encoder to degree/inch values
> Jackscrew is 8 turns per inch, Rotator gear ratio is 375:1

**Comment by acdelgado1019** [comment]
Constants and Commands complete - need to rebuild Subsystem class.
Required in class constructor:
- Create 3 motors
- Enable Soft Limits
- Set Soft Limits
- Set Current Limits
- Get Encoders
- Get PID Controllers
- Set P,I,D,IZone, FF, and Output range for both PID Controllers (P is a constant, Output range is constants, All others are 0)
- Set Position conversion factors for all 3 encoders
- Burn Flash to all 3 Motors

Methods required:

- Periodic (Don't forget too add @Override)
- Update Smart Dashboard
- Get Rotator
- Get Extender
- Get Claw
- Set Rotator
- Set Extender
- Set Claw
- Set Roller (Herron Prototype)
