### ISSUE TITLE
Create User Configurations

### ISSUE THREAD

**Issue by Wildcards7506** [Wildcards-7506/FRC-2023#5]
Requires: Player controller preferences

- Create playerconfigs folder in project
- Under playerconfigs, create PlayerConfigBase class with required variables (xMovement, yMovement, claw open/close, etc.) and empty getDriverConfig and getCoDriverConfig methods
- Create class for each operator, extend PlayerConfigBase, and use getDriver/getCoDriver config methods to assign buttons/joysticks to variables

**Comment by acdelgado1019** [comment]
Configs look good, continue to get other player's preferences and we will add them in.

Notes:
- Remove duplicate PlayerConfigs objects (Lines 53-56, HDD.java) and reuse objects in lines 48-51 in the sendable chooser options in lines 83-86
- Add driver and codriver objects near line 27 in Robot.java in the form "private PlayerConfigs variableName;"
- Set those driver and codriver configs in teleopInit in the form "varName = HDD.variable_chooser.getSelected();"
- Change lines 98 and 99 in Robot.java to refer to the created driver and codriver configurations
