### ISSUE TITLE
Command Development - LEDs

### ISSUE THREAD

**Issue by Wildcards7506** [Wildcards-7506/FRC-2023#8]
- Add LEDTOCom class to Commands folder
- Add controller logic to switch between lighting configurations

> Need controls to signal: 
> - Cone pickup (Solid Yellow)
> - Cube pickup (Solid Purple)
> - Limelight target detected but not aligned (Solid Orange)
> - Limelight target detected and aligned (Solid Green)
> - If none of these apply, light with team color (Blue or Red)

**Comment by galla416505** [comment]
Commands added, waiting for player Configuration.

**Comment by Wildcards7506** [comment]
Commands for Limelight Detection are on hold - This issue will stay open until Limelight is integrated
